manifest:
  remotes:
  - name: zmkfirmware
    url-base: https://github.com/zmkfirmware
  - name: lynnlee0522
    url-base: https://github.com/lynnlee0522
  - name: nxtkb
    url-base: https://github.com/nxtkb
  - name: aym1607
    url-base: https://github.com/AYM1607
  projects:
  - name: zmk
    remote: zmkfirmware
    revision: cb615aee9a7c427e251f2ab62080c1a44a165da9
    import: app/west.yml
  - name: zmk-vfx-sweep-pro-display
    remote: nxtkb
    revision: 7fa09a2ea91f94f7378acaf81b461197b01f4854
  - name: zmk-behavior-report
    remote: nxtkb
    revision: main
    import: west.yml
  - name: zmk-driver-azoteq-iqs5xx
    remote: aym1607
    revision: 27321f0232b50f0af31eb27ff97d539933467ea4
  self:
    path: config
